import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
	ClerkProvider,
	SignInButton,
	SignUpButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";
import { Heart } from "lucide-react";
import Link from "next/link";
import { Button } from "../components/ui/button";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
						<div className="container flex h-16 items-center justify-between py-4">
							<div className="flex items-center gap-2">
								<Heart className="h-6 w-6 text-teal-500" />
								<span className="text-xl font-bold">
									Mentalink
								</span>
							</div>
							<nav className="hidden md:flex gap-6">
								<Link
									href="#Rant"
									className="text-sm font-medium hover:text-teal-500 transition-colors"
								>
									Rant
								</Link>
								<Link
									href="#Emotion_Detection"
									className="text-sm font-medium hover:text-teal-500 transition-colors"
								>
									Emotion Detection
								</Link>
								<Link
									href="#"
									className="text-sm font-medium hover:text-teal-500 transition-colors"
								>
									Resources
								</Link>
								<Link
									href="#"
									className="text-sm font-medium hover:text-teal-500 transition-colors"
								>
									About
								</Link>
							</nav>
							<div className="flex items-center gap-4">
								<SignedOut>
									<Link
										href="/login"
										className="text-sm font-medium hover:text-teal-500 transition-colors hidden md:block"
									>
										Log in
									</Link>
									<Button
										asChild
										className="bg-teal-500 hover:bg-teal-600"
									>
										<Link href="/register">
											Get Started
										</Link>
									</Button>
								</SignedOut>
								<SignedIn>
									<UserButton />
								</SignedIn>
							</div>
						</div>
					</header>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
